### ISSUE TITLE
[Bug]: Android IL2Cpp Error

### ISSUE THREAD

**Issue by ds5678** [ds5678/AssetRipper#75]
### Describe the issue

This issue is most common on IL2Cpp Android games, but can occur on other platforms too. It has a signature stack trace:
```
General [Error] : Cpp2IL.Core.Exceptions.LibCpp2ILInitializationException: Fatal Exception initializing LibCpp2IL!
 ---> System.Exception: Pre-24.2 support for non-ARM ELF lookup is not yet implemented.
   at LibCpp2IL.Elf.ElfFile.FindCodeAndMetadataRegDefaultBehavior() in LibCpp2IL.dll:token 0x600016b+0xee
   at LibCpp2IL.Elf.ElfFile.FindCodeAndMetadataReg() in LibCpp2IL.dll:token 0x6000169+0xaf
   at LibCpp2IL.LibCpp2IlMain.Initialize(Byte[] binaryBytes, Byte[] metadataBytes, Int32[] unityVersion) in LibCpp2IL.dll:token 0x600007d+0x11d
   at LibCpp2IL.LibCpp2IlMain.LoadFromFile(String pePath, String metadataPath, Int32[] unityVersion) in LibCpp2IL.dll:token 0x600007e+0x7
   at Cpp2IL.Core.Cpp2IlApi.InitializeLibCpp2Il(String assemblyPath, String metadataPath, Int32[] unityVersion, Boolean allowUserToInputAddresses) in Cpp2IL.Core.dll:token 0x600004d+0x12
   --- End of inner exception stack trace ---
   at Cpp2IL.Core.Cpp2IlApi.InitializeLibCpp2Il(String assemblyPath, String metadataPath, Int32[] unityVersion, Boolean allowUserToInputAddresses) in Cpp2IL.Core.dll:token 0x600004d+0x35
   at AssetRipper.Core.Structure.Assembly.Managers.Il2CppManager.Initialize(PlatformGameStructure gameStructure) in E:\repos\AssetRipper\AssetRipperCore\Structure\Assembly\Managers\Il2CppManager.cs:line 24
   at AssetRipper.Core.Structure.GameStructure.GameStructure.Load(List`1 paths, CoreConfiguration configuration, LayoutInfo layinfo) in E:\repos\AssetRipper\AssetRipperCore\Structure\GameStructure\GameStructure.cs:line 91
   at AssetRipper.Core.Structure.GameStructure.GameStructure.Load(IEnumerable`1 paths, CoreConfiguration configuration, LayoutInfo layinfo) in E:\repos\AssetRipper\AssetRipperCore\Structure\GameStructure\GameStructure.cs:line 46
   at AssetRipper.Core.Structure.GameStructure.GameStructure.Load(IEnumerable`1 paths, CoreConfiguration configuration) in E:\repos\AssetRipper\AssetRipperCore\Structure\GameStructure\GameStructure.cs:line 38
   at AssetRipper.Library.Ripper.Load(IReadOnlyList`1 paths) in E:\repos\AssetRipper\AssetRipperLibrary\Ripper.cs:line 31
   at UnitTester.Program.RunTests() in E:\repos\AssetRipper\UnitTester\Program.cs:line 70
```
This error occurs because support for analyzing that type of assembly has not yet been implemented in [Cpp2IL](https://github.com/SamboyCoding/Cpp2IL).

There are plans to catch this error and switch to not exporting scripts, which would allow users to export these games that they previously could not. However, the catch has not yet been implemented into AssetRipper.

**Comment by ds5678** [comment]
This was fixed in one of the previous releases.

**Comment by mindphluxnet** [comment]
Still happens:

```
Unhandled exception. Cpp2IL.Core.Exceptions.LibCpp2ILInitializationException: Fatal Exception initializing LibCpp2IL!
 ---> System.Exception: Failed to find code registration or metadata registration!
   at LibCpp2IL.Il2CppBinary.Init(UInt64 pCodeRegistration, UInt64 pMetadataRegistration) in /home/runner/work/Cpp2IL/Cpp2IL/LibCpp2IL/Il2CppBinary.cs:line 80
   at LibCpp2IL.LibCpp2IlBinaryRegistry.CreateAndInit(Byte[] buffer, Il2CppMetadata metadata) in /home/runner/work/Cpp2IL/Cpp2IL/LibCpp2IL/LibCpp2IlBinaryRegistry.cs:line 72
   at LibCpp2IL.LibCpp2IlMain.Initialize(Byte[] binaryBytes, Byte[] metadataBytes, UnityVersion unityVersion) in /home/runner/work/Cpp2IL/Cpp2IL/LibCpp2IL/LibCpp2IlMain.cs:line 159
   at LibCpp2IL.LibCpp2IlMain.LoadFromFile(String pePath, String metadataPath, UnityVersion unityVersion) in /home/runner/work/Cpp2IL/Cpp2IL/LibCpp2IL/LibCpp2IlMain.cs:line 203
   at Cpp2IL.Core.Cpp2IlApi.InitializeLibCpp2Il(String assemblyPath, String metadataPath, UnityVersion unityVersion, Boolean allowUserToInputAddresses) in /_/Cpp2IL.Core/Cpp2IlApi.cs:line 61
   --- End of inner exception stack trace ---
   at Cpp2IL.Core.Cpp2IlApi.InitializeLibCpp2Il(String assemblyPath, String metadataPath, UnityVersion unityVersion, Boolean allowUserToInputAddresses) in /_/Cpp2IL.Core/Cpp2IlApi.cs:line 67
```

Game: https://store.steampowered.com/app/2445540/Monster_Rampage_VR/

**Comment by BB-VR** [comment]
@mindphluxnet did you find a fix i have your EXACT error
